### ISSUE TITLE
Feil størrelse på matriser

### ISSUE THREAD

**Issue by EdvardGrodem** [ttk21/ttk21_lecture-2_exercises#1]
I definisjonen av rotasjonsmatriser om enhets akser `def rot_x(cls, angle):` brukes en array av feil dimensjon noe som gir matriser av dybde 3.

Altså dette:
` 
        return cls.from_angle_axis(angle, np.array([[1, 0, 0]]).T)
`

må enders til:
` 
        return cls.from_angle_axis(angle, np.array([1, 0, 0]).T)
`

**Comment by tussedrotten** [comment]
Takk for hjelpen! Rot med [Rotation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_rotvec.html#scipy.spatial.transform.Rotation.from_rotvec) 😞 

Skal være fikset i 2fec46e
